# Generated by Django 6.0.2 on 2026-02-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteprofile',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='tech_stack',
            field=models.TextField(blank=True),
        ),
    ]
