# Generated by Django 6.0.2 on 2026-02-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_updated_at_siteprofile_update_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteprofile',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
