# Generated by Django 6.0.2 on 2026-02-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_update_at_siteprofile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(upload_to='hobbies/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
