# Generated by Django 6.0.2 on 2026-02-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_hobbyimage_siteprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='about_me',
            field=models.TextField(blank=True),
        ),
    ]
