# Generated by Django 6.0.2 on 2026-02-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_siteprofile_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(choices=[('philosophy', 'Chapter II — Philosophy'), ('teen', 'Chapter III — Teen'), ('adult', 'Chapter IV — Adult'), ('battles', 'Chapter V — Battles'), ('old', 'Chapter VI — Old (3 images)')], max_length=20)),
                ('image', models.ImageField(upload_to='chapters/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
